spring.application.name=backend

spring.profiles.include=private

# jpa
spring.jpa.hibernate.ddl-auto=update

# mysql
spring.datasource.url= ${MYSQL_URL}
spring.datasource.username= ${MYSQL_USERNAME}
spring.datasource.password= ${MYSQL_PASSWORD}

# mongodb
spring.data.mongodb.uri= ${MONGODB_URI}